# Generated by Django 3.2.7 on 2021-09-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fastfood',
            fields=[
                ('id', models.AutoField(db_column='index', primary_key=True, serialize=False)),
                ('address', models.CharField(db_column='address', default='', max_length=255)),
                ('categories', models.CharField(db_column='categories', default='', max_length=50)),
                ('city', models.CharField(db_column='city', default='', max_length=30)),
                ('country', models.CharField(db_column='country', default='', max_length=2)),
                ('name', models.CharField(db_column='name', default='', max_length=255)),
                ('postalCode', models.CharField(db_column='postalCode', default='', max_length=9)),
                ('province', models.CharField(db_column='province', default='', max_length=2)),
                ('websites', models.CharField(db_column='websites', default='', max_length=255)),
                ('latitude', models.FloatField(db_column='latitude')),
                ('longitude', models.FloatField(db_column='longitude')),
            ],
            options={
                'db_table': 'fast-food',
                'managed': False,
            },
        ),
    ]
